# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=30, verbose_name='昵称'),
        ),
    ]
