# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191105_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(null=True, verbose_name='登录时间'),
        ),
    ]
