# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=11, verbose_name='关注者')),
                ('b', models.CharField(max_length=11, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '关系表',
                'verbose_name_plural': '关系表',
                'db_table': 'relation',
            },
        ),
    ]
