# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='相册标题')),
                ('content', models.TextField(verbose_name='相册简介')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('likes', models.IntegerField(max_length=8, verbose_name='点赞数')),
                ('collects', models.IntegerField(max_length=8, verbose_name='收藏数')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '相册表',
                'verbose_name_plural': '相册表',
                'db_table': 'albums',
            },
        ),
    ]
