# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20191107_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='pictures', verbose_name='图片路径')),
                ('cover', models.BooleanField(default=False, verbose_name='封面')),
            ],
            options={
                'verbose_name': '图片表',
                'verbose_name_plural': '图片表',
                'db_table': 'pictures',
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='公开'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums'),
        ),
    ]
