# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20191108_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='collects',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
