# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_relation'),
        ('albums', '0004_auto_20191108_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('collected_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='收藏的相册')),
                ('collecter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '收藏表',
                'verbose_name_plural': '收藏表',
                'db_table': 'collections',
            },
        ),
    ]
